---
driver:
  name: vagrant
  synced_folders:
    - [".", "/tmp/chef-bib", "create: true"]

provisioner:
  name: shell

platforms:
  - name: arch
    driver:
      box: 'archlinux/archlinux'

suites:
  - name: default

busser:
  ruby_bindir: '/usr/bin'
