AllCops:
  Include:
    - Rakefile
    - cookbooks/**/*.rb

Style/ModuleFunction:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    "%i": '[]'
    "%I": '[]'
    "%r": '{}'
    "%w": '[]'
    "%W": '[]'
