default_role: kiosk
bib:
  base_url: 'http://umts.github.io/BusInfoBoard'
  stops: [64]
  routes: all
  excluded_trips:
    - Bus Garage via Mass Ave
    - Bus Garage via Compsci
  title: Bus Departures
